/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */

#ifdef _LIBC
# error Applications may not define the macro _LIBC
#endif

#define __stub___kernel_cosl __builtin_cirp_const_int(0, 1)
#define __stub___kernel_sinl __builtin_cirp_const_int(0, 1)
#define __stub___kernel_tanl __builtin_cirp_const_int(0, 1)
#define __stub_chflags
#define __stub_create_module __builtin_cirp_const_int(1, 0)
#define __stub_fattach
#define __stub_fchflags
#define __stub_fdetach
#define __stub_get_kernel_syms __builtin_cirp_const_int(1, 0)
#define __stub_getmsg __builtin_cirp_const_int(1, 0)
#define __stub_getpmsg __builtin_cirp_const_int(1, 0)
#define __stub_gtty
#define __stub_lchmod
#define __stub_putmsg __builtin_cirp_const_int(1, 0)
#define __stub_putpmsg __builtin_cirp_const_int(1, 0)
#define __stub_query_module __builtin_cirp_const_int(1, 0)
#define __stub_revoke
#define __stub_setlogin
#define __stub_sigreturn
#define __stub_sstk
#define __stub_stty
